### PR TITLE
Add Razzle and Vue

### LINKED ISSUE #4: "this will run npm undefined"
just a visual bug, it still works fine!

image

seen when doing a regular create-react-app

### PR DESCRIPTION
**Pull request by SaraVieira**
Hey! 👋

This PR adds two new thingies:

Razzle: https://github.com/jaredpalmer/razzle
Vue with the CLI: https://github.com/vuejs/vue-cli/

Also added yarn.lock to gitignore and added node_modules to it

Also closes #4 as the problem was that we need to be explicit in the constants that we are going to run start

### CODE REVIEW

**Comment by jxnblk** [comment]
Awesome thanks! One small nit: is it easy to undo the tab size changes? If not I can `gg=G` after merging

**Comment by SaraVieira** [comment]
Fixed ! Sorry about that, it's the defaults in my vscode :(

**Comment by SaraVieira** [comment]
Added ability to open in editor so closes #6

**Comment by jxnblk** [comment]
Thanks again! This looks great!

**Comment by vesparny** [comment]
Hey @SaraVieira, just out of curiosity, why did you ignore the `yarn.lock` file?

**Comment by SaraVieira** [comment]
Hey!

Mostly because there was no package.lock and I didn't know if @jxnblk wanted a lock file

**Comment by vesparny** [comment]
Ah ok, cheers

**Pull request merged**
